SET lc_messages TO 'en_US.UTF-8';

DO $$ BEGIN INSERT INTO lookups."code_snippet_category" (value,dec_en,dec_es,dec_pt,dec_it,sort_order,mandatory_flag) VALUES ('form_action','Form Action','Form Action','Form Action','Form Action',NULL,FALSE); EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN INSERT INTO lookups."code_snippet_category" (value,dec_en,dec_es,dec_pt,dec_it,sort_order,mandatory_flag) VALUES ('form_variable','Form Variable','Form Action','Form Action','Form Action',NULL,FALSE); EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN INSERT INTO lookups."code_snippet_category" (value,dec_en,dec_es,dec_pt,dec_it,sort_order,mandatory_flag) VALUES ('global_action','Global Action','Global Action','Global Action','Global Action',NULL,FALSE); EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN INSERT INTO lookups."code_snippet_category" (value,dec_en,dec_es,dec_pt,dec_it,sort_order,mandatory_flag) VALUES ('global_variable','Global Variable','Global Action','Global Action','Global Action',NULL,FALSE); EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN INSERT INTO lookups."code_snippet_category" (value,dec_en,dec_es,dec_pt,dec_it,sort_order,mandatory_flag) VALUES ('lister_action','Lister Action','Lister Action','Lister Action','Lister Action',NULL,FALSE); EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN INSERT INTO lookups."code_snippet_category" (value,dec_en,dec_es,dec_pt,dec_it,sort_order,mandatory_flag) VALUES ('lister_variable','Lister Variable','Lister Action','Lister Action','Lister Action',NULL,FALSE); EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN INSERT INTO lookups."code_snippet_category" (value,dec_en,dec_es,dec_pt,dec_it,sort_order,mandatory_flag) VALUES ('widget_action','Widget Action','Widget Action','Widget Action','Widget Action',NULL,FALSE); EXCEPTION WHEN OTHERS THEN END; $$;
DO $$ BEGIN INSERT INTO lookups."code_snippet_category" (value,dec_en,dec_es,dec_pt,dec_it,sort_order,mandatory_flag) VALUES ('widget_variable','Widget Variable','Widget Action','Widget Action','Widget Action',NULL,FALSE); EXCEPTION WHEN OTHERS THEN END; $$;
